#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPISearchReferenceMapping
@end

@interface JSAPISearchReferenceMapping : JSAPIObject

/* Unique identifier for the mapping to protect against duplicates 
 */
@property(nonatomic) NSString* _id;
/* The field that will be replaced with the refType 
 */
@property(nonatomic) NSString* varNewFieldName;
/* The path to the id of the referenced resource (can be a field name, or dot notation for sub-fields) 
 */
@property(nonatomic) NSString* refIdField;
/* The index type that the mapping pulls data from 
 */
@property(nonatomic) NSString* refType;
/* The index type that the mapping is for 
 */
@property(nonatomic) NSString* type;

+ (NSDictionary *)modalDictionary;

@end
