#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIInnerQuery.h"
@protocol JSAPIInnerQuery;
@class JSAPIInnerQuery;



@protocol JSAPISearchQuery
@end

@interface JSAPISearchQuery : JSAPIObject

/* Index of the first result to be returned for pagination [optional]
 */
@property(nonatomic) NSNumber* from;
/* The query body 
 */
@property(nonatomic) JSAPIInnerQuery* query;
/* The maximum number of results to be returned for pagination [optional]
 */
@property(nonatomic) NSNumber* size;
/* Elasticsearch sort [optional]
 */
@property(nonatomic) NSObject* sort;
/* Elasticsearch source [optional]
 */
@property(nonatomic) NSObject* source;

+ (NSDictionary *)modalDictionary;

@end
