#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPISearchReferenceMapping.h"
@protocol JSAPISearchReferenceMapping;
@class JSAPISearchReferenceMapping;



@protocol JSAPISearchObjectDefinition
@end

@interface JSAPISearchObjectDefinition : JSAPIObject

/* The relative URL of the service that will provide the initial data to index. Assumed to be compliant with KnetikCloud pagination standards. Ex: /locations. [optional]
 */
@property(nonatomic) NSString* dataSupplierUrl;
/* The name of the field representing the unique identifier of the document. Ex: UserResource -> id [optional]
 */
@property(nonatomic) NSString* idField;
/* Describe how nested resources should be mapped to documents if needed. Search service will copy the already indexed dependant documents and use them to replace the listed fields at runtime. Ex: comment.user is a user document [optional]
 */
@property(nonatomic) NSArray<JSAPISearchReferenceMapping>* mappings;
/* The name of the property that holds the template ID for custom objects. (ex: template or template_id) [optional]
 */
@property(nonatomic) NSString* templateField;
/* The name of the index where the documents will be stored. Be convention, the name of the resource w/o suffix. Ex: UserResource -> users [optional]
 */
@property(nonatomic) NSString* type;

+ (NSDictionary *)modalDictionary;

@end
