#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIProperty.h"
#import "JSAPISimpleUserResource.h"
@protocol JSAPIProperty;
@class JSAPIProperty;
@protocol JSAPISimpleUserResource;
@class JSAPISimpleUserResource;



@protocol JSAPIVerificationRequest
@end

@interface JSAPIVerificationRequest : JSAPIObject

/* A map of additional properties, keyed on the property name.  Must match the names and types defined in the template for this item type [optional]
 */
@property(nonatomic) NSDictionary* additionalProperties;
/* A unique code to identify the request. May be publically known and use ACL to require the correct user to respond, or private and the ACL allows anyone with the code to verify. default: random [optional]
 */
@property(nonatomic) NSString* code;
/* The intended length of the code, if auto-generated. Minimum 3, default 16 [optional]
 */
@property(nonatomic) NSNumber* codelength;
/* The date/time this resource was created in seconds since unix epoch [optional]
 */
@property(nonatomic) NSNumber* createdDate;
/* The date, as a unix timestamp in seconds, that the request expires [optional]
 */
@property(nonatomic) NSNumber* expirationDate;
/* Whether to include numbers, if the code is auto-generated. Default: true [optional]
 */
@property(nonatomic) NSNumber* includeNumbers;
/* An optional user that is expected to respond [optional]
 */
@property(nonatomic) JSAPISimpleUserResource* targetUser;
/* A template this verification request is validated against. Filled from url [optional]
 */
@property(nonatomic) NSString* template;
/* The date/time this resource was last updated in seconds since unix epoch [optional]
 */
@property(nonatomic) NSNumber* updatedDate;

+ (NSDictionary *)modalDictionary;

@end
