#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIAccessEntryResource
@end

@interface JSAPIAccessEntryResource : JSAPIObject

/* The actions that users with the sid can take on this resource. Must match with actions available for the type of resource 
 */
@property(nonatomic) NSArray<NSString*>* actions;
/* Optional list of fields, in JSON Pointer notation (RFC 6901), that are not to be granted the associated actions for. Specifically, this affects LIST, GET, PUT, and POST by not allowing retrieval, edit, or creation of the field. For LIST the fields stripped from return objects based on parent ACL. The ACL is always additive, thus other access entries may grant these actions on these fields anyways [optional]
 */
@property(nonatomic) NSArray<NSString*>* fieldBlacklist;
/* The security id that gets this level of access. Security ids are prefixed with a type, foollowed by a hyphen, then an id. Formats: user-ID, group-UNIQUE_NAME, friend-USER_ID and role-ROLE 
 */
@property(nonatomic) NSString* sid;

+ (NSDictionary *)modalDictionary;

@end
