#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIMonitoringIncidentLevelResource.h"
#import "JSAPISimpleReferenceResourceString_.h"
@protocol JSAPIMonitoringIncidentLevelResource;
@class JSAPIMonitoringIncidentLevelResource;
@protocol JSAPISimpleReferenceResourceString_;
@class JSAPISimpleReferenceResourceString_;



@protocol JSAPIMonitoringIncidentResource
@end

@interface JSAPIMonitoringIncidentResource : JSAPIObject

/* The alert this incident is for 
 */
@property(nonatomic) JSAPISimpleReferenceResourceString_* alert;
/* The name of the current alert level 
 */
@property(nonatomic) NSString* currentLevel;
/* The endDate as a unix timestamp in seconds the incident was manually ended. Null if still open [optional]
 */
@property(nonatomic) NSNumber* endDate;
/* The id of the incident. Cannot be changed 
 */
@property(nonatomic) NSString* _id;
/* Whether the most recent check for any level had too little data to determine status, and alert level missing_data_policy is 'missing' [optional]
 */
@property(nonatomic) NSNumber* insufficientData;
/* The statuses of each level 
 */
@property(nonatomic) NSArray<JSAPIMonitoringIncidentLevelResource>* levels;
/* The startDate as a unix timestamp in seconds the incident first started [optional]
 */
@property(nonatomic) NSNumber* startDate;

+ (NSDictionary *)modalDictionary;

@end
