#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIMonitoringAlertLevel
@end

@interface JSAPIMonitoringAlertLevel : JSAPIObject

/* The number of seconds to wait for a certain duration between first encountering a new expression output vector element and counting an alert as firing for this element. 
 */
@property(nonatomic) NSNumber* duration;
/* The expression to run. Docs: https://prometheus.io/docs/prometheus/latest/querying/functions/ 
 */
@property(nonatomic) NSString* expression;
/* The name of the alert level 
 */
@property(nonatomic) NSString* name;

+ (NSDictionary *)modalDictionary;

@end
