#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIDocumentRemoveRequest
@end

@interface JSAPIDocumentRemoveRequest : JSAPIObject

/* The id of the document [optional]
 */
@property(nonatomic) NSString* _id;
/* The id of the template if this document is based on a templated resource [optional]
 */
@property(nonatomic) NSString* template;
/* The type of document [optional]
 */
@property(nonatomic) NSString* type;

+ (NSDictionary *)modalDictionary;

@end
