#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIMonitoringIncidentEventResource
@end

@interface JSAPIMonitoringIncidentEventResource : JSAPIObject

/* The id of the alert 
 */
@property(nonatomic) NSString* alertId;
/* The date as a unix timestamp in seconds for the event [optional]
 */
@property(nonatomic) NSNumber* date;
/* The id of the incident event [optional]
 */
@property(nonatomic) NSString* _id;
/* The id of the incident. will be added to any current incident for the alert or a new one created [optional]
 */
@property(nonatomic) NSString* incidentId;
/* The name of the alert level 
 */
@property(nonatomic) NSString* levelName;
/* The new status of the alert level 
 */
@property(nonatomic) NSString* status;
/* The value that triggered the alarm [optional]
 */
@property(nonatomic) NSString* triggerValue;

+ (NSDictionary *)modalDictionary;

@end
