#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIPatchActionResource.h"
@protocol JSAPIPatchActionResource;
@class JSAPIPatchActionResource;



@protocol JSAPIPatchResource
@end

@interface JSAPIPatchResource : JSAPIObject

/* The list of patch actions to perform on a resource 
 */
@property(nonatomic) NSArray<JSAPIPatchActionResource>* patchActions;

+ (NSDictionary *)modalDictionary;

@end
