#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIMonitoringMetricDatapointResource
@end

@interface JSAPIMonitoringMetricDatapointResource : JSAPIObject

/* Dimensions giving context to the datapoint. Map of keys to values (example: {\"location\": \"USA\", \"user\": \"75\"}). Cannot include the | symbol [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* dimensions;
/* The unix timestamp in seconds the datapoint occurred, default: now [optional]
 */
@property(nonatomic) NSNumber* timestamp;
/* The value of the datapoint 
 */
@property(nonatomic) NSNumber* value;

+ (NSDictionary *)modalDictionary;

@end
