#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIMonitoringMetricRecordResource
@end

@interface JSAPIMonitoringMetricRecordResource : JSAPIObject

/* Dimensions giving context to the datapoint. Map of keys to values (example: {\"location\": \"USA\", \"user\": \"75\"}). Cannot include the | symbol [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* dimensions;

+ (NSDictionary *)modalDictionary;

@end
