#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIClientCustomizationResource
@end

@interface JSAPIClientCustomizationResource : JSAPIObject

/* The text displayed above the login form for the login page.  Default: Enter your credentials [optional]
 */
@property(nonatomic) NSString* credentialText;
/* The link to a custom css file for the login page.  If not using, keep it set as null. [optional]
 */
@property(nonatomic) NSString* customCssUrl;
/* The link to a favicon ico for the login page.  If not using, keep it set as null. [optional]
 */
@property(nonatomic) NSString* faviconUrl;
/* The HTML inside the header for the login page.  If not using, keep it set as null. [optional]
 */
@property(nonatomic) NSString* footer;
/* The text provided for the link for a forgotten username for the login page.  Default: Forgot password? [optional]
 */
@property(nonatomic) NSString* forgotPasswordText;
/* The link to a forgot password page for the login page.  If not using, keep it set as null. [optional]
 */
@property(nonatomic) NSString* forgotPasswordUrl;
/* The text provided for the link for a forgotten username for the login page.  Default: Forgot username? [optional]
 */
@property(nonatomic) NSString* forgotUsernameText;
/* The link to a forgot username page for the login page.  If not using, keep it set as null. [optional]
 */
@property(nonatomic) NSString* forgotUsernameUrl;
/* The HTML inside the header for the login page.  If not using, keep it set as null. [optional]
 */
@property(nonatomic) NSString* header;
/* The text displayed when inputting an invalid user/pass for the login page.  Default: Invalid username or password. [optional]
 */
@property(nonatomic) NSString* invalidLoginText;
/* The text displayed on the login button for the login page.  Default: Log In [optional]
 */
@property(nonatomic) NSString* loginButtonText;
/* The text displayed when logging out for the login page.  Default: You have been logged out. [optional]
 */
@property(nonatomic) NSString* logoutText;
/* The placeholder text in the password entry for the login page.  Default: Password [optional]
 */
@property(nonatomic) NSString* passwordPlaceholder;
/* The text displayed when there are auth providers to select from for the login page.  Default: Or use your favorite identity provider [optional]
 */
@property(nonatomic) NSString* providerText;
/* The text provided for the link to sign up for the login page.  Default: Sign up [optional]
 */
@property(nonatomic) NSString* signUpText;
/* The link to a sign up url for the login page.  If not using, keep it set as null. [optional]
 */
@property(nonatomic) NSString* signUpUrl;
/* The title of the login page.  If not using, keep it set as null. [optional]
 */
@property(nonatomic) NSString* title;
/* The placeholder text in the username entry for the login page.  Default: Username [optional]
 */
@property(nonatomic) NSString* usernamePlaceholder;

+ (NSDictionary *)modalDictionary;

@end
