#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIAccessEntryResource.h"
@protocol JSAPIAccessEntryResource;
@class JSAPIAccessEntryResource;



@protocol JSAPIAccessResourceCreateRequest
@end

@interface JSAPIAccessResourceCreateRequest : JSAPIObject

/* The access list for the resource. If null on create, will take default from type [optional]
 */
@property(nonatomic) NSArray<JSAPIAccessEntryResource>* access;
/* The id of the resource we are defining access for 
 */
@property(nonatomic) NSString* _id;
/* The id of the parent resource (null if parent top level) [optional]
 */
@property(nonatomic) NSString* parentId;
/* The type of the parent resource (null for top level) 
 */
@property(nonatomic) NSString* parentType;
/* Sid placeholders mapped to sid replacement value. Useful for injecting owner/creator id. [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* sidReplacements;

+ (NSDictionary *)modalDictionary;

@end
