#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol JSAPIQuickPaidRequest
@end

@interface JSAPIQuickPaidRequest : JSAPIObject

/* An optional target user to give the item to as a gift 
 */
@property(nonatomic) NSNumber* giftTarget;
/* An optional note to add to the item [optional]
 */
@property(nonatomic) NSString* itemNotes;
/* The amount already paid. Must match final price to complete purchase. Minimum 0 
 */
@property(nonatomic) NSNumber* paidAmount;
/* Override the price of an item, if the behavior configuration permits it. Do not send if taking standard pricing. Minimum 0 [optional]
 */
@property(nonatomic) NSNumber* priceOverride;
/* SKU of item being purchased 
 */
@property(nonatomic) NSString* sku;
/* Transaction details [optional]
 */
@property(nonatomic) NSString* transactionDetails;
/* Transaction type 
 */
@property(nonatomic) NSString* transactionType;
/* ID of the user making the purchase. If null, currently logged in user will be used. [optional]
 */
@property(nonatomic) NSNumber* userId;

+ (NSDictionary *)modalDictionary;

@end
