#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIProperty.h"
@protocol JSAPIProperty;
@class JSAPIProperty;



@protocol JSAPIQuickPaidRequest
@end

@interface JSAPIQuickPaidRequest : JSAPIObject

/* A map of additional properties, keyed on the property name (private). Must match the names and types defined in the template for this invoice type, or be an extra not from the template [optional]
 */
@property(nonatomic) NSDictionary* additionalProperties;
/* Line one of the customer's shipping address [optional]
 */
@property(nonatomic) NSString* address1;
/* Line two of the customer's shipping address [optional]
 */
@property(nonatomic) NSString* address2;
/* Line one of the customer's billing address [optional]
 */
@property(nonatomic) NSString* billingAddress1;
/* Line two of the customer's billing address [optional]
 */
@property(nonatomic) NSString* billingAddress2;
/* The city for the customer's billing address [optional]
 */
@property(nonatomic) NSString* billingCityName;
/* The country for the customer's billing address [optional]
 */
@property(nonatomic) NSString* billingCountryName;
/* The customer's name for the billing address [optional]
 */
@property(nonatomic) NSString* billingFullName;
/* The postal code for the customer's billing address [optional]
 */
@property(nonatomic) NSString* billingPostalCode;
/* The state for the customer's billing address [optional]
 */
@property(nonatomic) NSString* billingStateName;
/* The city for the customer's shipping address [optional]
 */
@property(nonatomic) NSString* cityName;
/* The country for the customer's shipping address [optional]
 */
@property(nonatomic) NSString* countryName;
/* The customer's email address [optional]
 */
@property(nonatomic) NSString* email;
/* The amount of federal tax to add (increases final price of invoice even if using price override). Minimum 0 [optional]
 */
@property(nonatomic) NSNumber* federalTax;
/* An optional target user to give the item to as a gift 
 */
@property(nonatomic) NSNumber* giftTarget;
/* An optional note to add to the item [optional]
 */
@property(nonatomic) NSString* itemNotes;
/* The customer's name prefix [optional]
 */
@property(nonatomic) NSString* namePrefix;
/* The amount already paid. Must match final price to complete purchase. Ignored for non-paid endpoints. Minimum 0 [optional]
 */
@property(nonatomic) NSNumber* paidAmount;
/* The postal code for the customer's shipping address [optional]
 */
@property(nonatomic) NSString* postalCode;
/* Override the price of an item, if the behavior configuration permits it. Do not send if taking standard pricing. Minimum 0 [optional]
 */
@property(nonatomic) NSNumber* priceOverride;
/* SKU of item being purchased 
 */
@property(nonatomic) NSString* sku;
/* The state for the customer's shipping address [optional]
 */
@property(nonatomic) NSString* stateName;
/* The amount of state tax to add (increases final price of invoice even if using price override). Minimum 0 [optional]
 */
@property(nonatomic) NSNumber* stateTax;
/* An invoice template this invoice is validated against (private). May be null and no validation of properties will be done [optional]
 */
@property(nonatomic) NSString* template;
/* Transaction details [optional]
 */
@property(nonatomic) NSString* transactionDetails;
/* Transaction type 
 */
@property(nonatomic) NSString* transactionType;
/* ID of the user making the purchase. If null, currently logged in user will be used. [optional]
 */
@property(nonatomic) NSNumber* userId;

+ (NSDictionary *)modalDictionary;

@end
