#import <Foundation/Foundation.h>
#import "JSAPIObject.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "JSAPIMonitoringAlertLevel.h"
#import "JSAPISimpleReferenceResourceString_.h"
@protocol JSAPIMonitoringAlertLevel;
@class JSAPIMonitoringAlertLevel;
@protocol JSAPISimpleReferenceResourceString_;
@class JSAPISimpleReferenceResourceString_;



@protocol JSAPIMonitoringAlertResource
@end

@interface JSAPIMonitoringAlertResource : JSAPIObject

/* Whether the alert is live and should be evaluated. Default: true [optional]
 */
@property(nonatomic) NSNumber* enabled;
/* The id of the alert. Cannot be changed 
 */
@property(nonatomic) NSString* _id;
/* The levels of alert to raise. Minimum 1 and maximum 10 entries. The alert level will be the one with the last one in the list that is passed its threshold 
 */
@property(nonatomic) NSArray<JSAPIMonitoringAlertLevel>* levels;
/* The name of a label returned in the alert query that is used to merge multiple incidents when they match [optional]
 */
@property(nonatomic) NSString* mergeLabel;
/* The id of the metric the alert is monitoring [optional]
 */
@property(nonatomic) JSAPISimpleReferenceResourceString_* metric;
/* The name of the alert, for display purposes 
 */
@property(nonatomic) NSString* name;

+ (NSDictionary *)modalDictionary;

@end
