#import <Foundation/Foundation.h>
#import "JSAPIBasicTemplatedResource.h"
#import "JSAPIPageResourceTemplateResource_.h"
#import "JSAPIPatchResource.h"
#import "JSAPIResult.h"
#import "JSAPITemplateResource.h"
#import "JSAPIApi.h"

/**
* Knetik Platform API Documentation latest 
* This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
*
* OpenAPI spec version: latest 
* Contact: support@knetik.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface JSAPITemplatesApi: NSObject <JSAPIApi>

extern NSString* kJSAPITemplatesApiErrorDomain;
extern NSInteger kJSAPITemplatesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(JSAPIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create a template
/// <b>Permissions Needed:</b> TEMPLATES_ADMIN<br /><b>Permissions Needed:</b> POST
///
/// @param typeHint The type for the resource this template applies to
/// @param template The template (optional)
/// 
///  code:201 message:"Created",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return JSAPITemplateResource*
-(NSURLSessionTask*) createTemplateWithTypeHint: (NSString*) typeHint
    template: (JSAPITemplateResource*) template
    completionHandler: (void (^)(JSAPITemplateResource* output, NSError* error)) handler;


/// Delete a template
/// <b>Permissions Needed:</b> TEMPLATES_ADMIN<br /><b>Permissions Needed:</b> DELETE
///
/// @param typeHint The type for the resource this template applies to
/// @param _id The id of the template
/// @param cascade How to cascade the delete (optional)
/// 
///  code:204 message:"No Content",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return void
-(NSURLSessionTask*) deleteTemplateWithTypeHint: (NSString*) typeHint
    _id: (NSString*) _id
    cascade: (NSString*) cascade
    completionHandler: (void (^)(NSError* error)) handler;


/// Get a template
/// <b>Permissions Needed:</b> TEMPLATES_ADMIN<br /><b>Permissions Needed:</b> GET
///
/// @param typeHint The type for the resource this template applies to
/// @param _id The id of the template
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return JSAPITemplateResource*
-(NSURLSessionTask*) getTemplateWithTypeHint: (NSString*) typeHint
    _id: (NSString*) _id
    completionHandler: (void (^)(JSAPITemplateResource* output, NSError* error)) handler;


/// List and search templates
/// <b>Permissions Needed:</b> TEMPLATES_ADMIN<br /><b>Permissions Needed:</b> LIST
///
/// @param typeHint The type for the resource this template applies to
/// @param size The number of objects returned per page (optional) (default to 25)
/// @param page The number of the page returned, starting with 1 (optional) (default to 1)
/// @param order A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional) (default to id:ASC)
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return JSAPIPageResourceTemplateResource_*
-(NSURLSessionTask*) getTemplatesWithTypeHint: (NSString*) typeHint
    size: (NSNumber*) size
    page: (NSNumber*) page
    order: (NSString*) order
    completionHandler: (void (^)(JSAPIPageResourceTemplateResource_* output, NSError* error)) handler;


/// Patch a template
/// <b>Permissions Needed:</b> TEMPLATES_ADMIN<br /><b>Permissions Needed:</b> PUT
///
/// @param typeHint The type for the resource this template applies to
/// @param _id The id of the template
/// @param templatePatchResource The patch resource object (optional)
/// @param testValidation If true, this will test validation but not submit the patch request (optional)
/// 
///  code:204 message:"No Content",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden"
///
/// @return void
-(NSURLSessionTask*) patchTemplateWithTypeHint: (NSString*) typeHint
    _id: (NSString*) _id
    templatePatchResource: (JSAPIPatchResource*) templatePatchResource
    testValidation: (NSNumber*) testValidation
    completionHandler: (void (^)(NSError* error)) handler;


/// Validate a templated resource
/// Error code thrown if invalid.<br><br><b>Permissions Needed:</b> TEMPLATES_ADMIN<br /><b>Permissions Needed:</b> GET
///
/// @param typeHint The type for the resource this template applies to
/// @param resource The resource to validate (optional)
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return void
-(NSURLSessionTask*) validateWithTypeHint: (NSString*) typeHint
    resource: (JSAPIBasicTemplatedResource*) resource
    completionHandler: (void (^)(NSError* error)) handler;



@end
